In [12]:
import numpy as np 
from scipy.linalg import lu
## decomposition 

a = np.arange(1, 5*5+1).reshape(5, 5)
print("triangular upper: \n{}".format(np.triu(a)))
print("triangular lower: \n{}".format(np.tril(a)))

 = lu(a)
print(l)

triangular upper: 
[[ 1  2  3  4  5]
 [ 0  7  8  9 10]
 [ 0  0 13 14 15]
 [ 0  0  0 19 20]
 [ 0  0  0  0 25]]
triangular lower: 
[[ 1  0  0  0  0]
 [ 6  7  0  0  0]
 [11 12 13  0  0]
 [16 17 18 19  0]
 [21 22 23 24 25]]


ValueError: too many values to unpack (expected 2)