In [138]:
import numpy as np 

ns = [10**i for i in range(1, 8)]
for n in ns:
    mat1 = np.random.uniform(-1, 1, (n, 2))
    result = np.apply_along_axis(lambda x: 1 if (x[0]**2+x[1]**2)<1 else 0, axis=1, arr=mat1)
    print(f"n:{n:8d}, estimated pi: {np.sum(result)/n*4:13.12f}")

n:      10, estimated pi: 2.400000000000
n:     100, estimated pi: 3.200000000000
n:    1000, estimated pi: 3.116000000000
n:   10000, estimated pi: 3.143200000000
n:  100000, estimated pi: 3.137280000000
n: 1000000, estimated pi: 3.142656000000
n:10000000, estimated pi: 3.141124800000


AttributeError: 'function' object has no attribute 'ndim'

In [46]:
x**1

array([[ 0.05725751,  0.38095672],
       [-0.23635123, -0.43922627],
       [ 0.58887888,  0.7976535 ],
       [ 0.34659228,  0.03708952],
       [-0.01350175,  0.31983868],
       [ 0.04752634, -0.32263679],
       [-0.22895275,  0.71006657],
       [ 0.54685752, -0.42431271],
       [ 0.29168597, -0.89431619],
       [-0.81157513, -0.57504059]])

In [47]:
a = np.array([[1, 2], [3, 4]])
a*82

array([[ 82, 164],
       [246, 328]])

In [37]:
x.dot(x)

ValueError: shapes (10,2) and (10,2) not aligned: 2 (dim 1) != 10 (dim 0)

In [73]:
import numpy as np 

mat1 = np.array([[1,2,3], 
                 [4,5,6]])
print(mat1)
print(mat1.shape)

np.apply_along_axis(func1d=lambda x: x+1, axis=1, arr=mat1)

[[1 2 3]
 [4 5 6]]
(2, 3)


array([[2, 3, 4],
       [5, 6, 7]])

In [94]:
import numpy as np 

a = np.arange(24).reshape(2,3,4)
print(f"shape: {a.shape}")
print(a)
print("=="*20)
result = np.apply_along_axis(func1d=np.sum, axis=0, arr=a)
print(f"shape: {result.shape}")
print(result)
print("=="*20)
result = np.apply_along_axis(func1d=np.sum, axis=1, arr=result)
print(f"shape: {result.shape}")
print(result)

shape: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
shape: (3, 4)
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
shape: (3,)
[ 60  92 124]


In [208]:
from anytree import Node, RenderTree

## 가능하면 아래처럼 node set list를 하나 만들어서 관리해주는 것이 편함. 
all_node_set = []

## 새로운 변수를 추가해서 넣어줘도 상관없음. 
## 단 하나의 어떤 node에 data가 있을 경우 아래 모든 노드에서도 data를 넣어주어야 함
root = Node("root", data=0)

all_node_set.append(root)

for i in range(0, 3):
    ## root.children은 기본적으로 tuple구조이며, 따라서 append등으로 새로운 값을 넣어줄 수 없음
    ## 대신 아래처럼 새로운 node를 만들고, parent를 지정해주면 알아서 연결됨 
    new_node = Node(f'child_{i}', parent=root, data=0)
    ## child가 추가되면 data를 변경하도록 세팅 
    root.data+=1
    all_node_set.append(new_node)
Node("child_child_1", parent=root.children[0], data=0)

print("=="*20)
## text상에서, tree를 예쁘게 볼 수 있음. 
for row in RenderTree(root):
    pre, fill, node = row
    print(f"{pre}{node.name}, data: {node.data}")
print("=="*20)
## 기본적인 tree method를 지원
print(f"children: { [c.name for c in root.children] }")
print(f"parent: {root.children[0].parent}")
print(f"is_root: {root.is_root}")
print(f"is_leaf: {root.is_leaf}")
## path ==> root부터 target_Node까지의 길을 말함. 
target_node = root.children[0].children[0]
print(f"path: {target_node.path}")
print(f"ancestors: {target_node.ancestors}")
print("=="*20)




root, data: 3
├── child_0, data: 0
│   └── child_child_1, data: 0
├── child_1, data: 0
└── child_2, data: 0
children: ['child_0', 'child_1', 'child_2']
parent: Node('/root', data=3)
is_root: True
is_leaf: False
path: (Node('/root', data=3), Node('/root/child_0', data=0), Node('/root/child_0/child_child_1', data=0))
ancestors: (Node('/root', data=3), Node('/root/child_0', data=0))


In [206]:
## with node mixin

from anytree import NodeMixin, RenderTree
class MyBaseClass(object):
    pass

## MyBaseClass 대신에 object를 넣어도 상관없을 것이라고 생각했는데, 안됨. 
class MyClass(MyBaseClass, NodeMixin):
    def __init__(self, name, gender, parent=None):
        self.name=name
        self.gender=gender
        self.parent=parent## 이 부분만 유의해서 넣어주면 됨. 
    def __repr__(self):
        return self.name
        
root = MyClass(name='root', gender=None, parent=None)
mother = MyClass(name='mother', gender='female', parent=root)
brother = MyClass(name='brother', gender='male', parent=mother)
me = MyClass(name='me', gender='male', parent=mother)

for row in RenderTree(root):
    pre, fill, node = row
    print(f"{pre}{node}")
print("=="*20)
## 기존 Node에서 쓰던 method를 그대로 사용할 수 있음. 
print(f"me.ancestors: {me.ancestors}")
print(f"mother.children: {mother.children}")

root
└── mother
    ├── brother
    └── me
me.ancestors: (root, mother)
mother.children: (brother, me)


In [197]:
class aa(): pass