In [1]:
"""
axis 0, axis 1을 공부합시다. 
np.sum np.any np.all 

그리고, 이게 2차원이 아닌 경우(for tensorflow )
"""


''

In [25]:
import numpy as np

"""차원에 따른 변화를 파악하기 위해서 각 축을 소수로 만들어서 4차원의 어레이를 생성
"""
test_arr = np.array([i for i in range(0, 2*3*5*7)]).reshape(2,3,5,7)
print("shape: {}".format(test_arr.shape))
print("---")
print(test_arr)



shape: (2, 3, 5, 7)
---
[[[[  0   1   2   3   4   5   6]
   [  7   8   9  10  11  12  13]
   [ 14  15  16  17  18  19  20]
   [ 21  22  23  24  25  26  27]
   [ 28  29  30  31  32  33  34]]

  [[ 35  36  37  38  39  40  41]
   [ 42  43  44  45  46  47  48]
   [ 49  50  51  52  53  54  55]
   [ 56  57  58  59  60  61  62]
   [ 63  64  65  66  67  68  69]]

  [[ 70  71  72  73  74  75  76]
   [ 77  78  79  80  81  82  83]
   [ 84  85  86  87  88  89  90]
   [ 91  92  93  94  95  96  97]
   [ 98  99 100 101 102 103 104]]]


 [[[105 106 107 108 109 110 111]
   [112 113 114 115 116 117 118]
   [119 120 121 122 123 124 125]
   [126 127 128 129 130 131 132]
   [133 134 135 136 137 138 139]]

  [[140 141 142 143 144 145 146]
   [147 148 149 150 151 152 153]
   [154 155 156 157 158 159 160]
   [161 162 163 164 165 166 167]
   [168 169 170 171 172 173 174]]

  [[175 176 177 178 179 180 181]
   [182 183 184 185 186 187 188]
   [189 190 191 192 193 194 195]
   [196 197 198 199 200 201 202]
   [203

In [46]:
new_arr = np.min(test_arr, axis=None)
print("axis=None:")
print("shape: {}".format(new_arr.shape))
print(new_arr)
print("---")
for axis_v in range(0, len(test_arr.shape)):
    new_arr = np.min(test_arr, axis=axis_v)
    print("axis={}:".format(axis_v))
    print("shape: {}".format(new_arr.shape))
    print(new_arr)
    print("---")

axis=None:
shape: ()
0
---
axis=0:
shape: (3, 5, 7)
[[[  0   1   2   3   4   5   6]
  [  7   8   9  10  11  12  13]
  [ 14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27]
  [ 28  29  30  31  32  33  34]]

 [[ 35  36  37  38  39  40  41]
  [ 42  43  44  45  46  47  48]
  [ 49  50  51  52  53  54  55]
  [ 56  57  58  59  60  61  62]
  [ 63  64  65  66  67  68  69]]

 [[ 70  71  72  73  74  75  76]
  [ 77  78  79  80  81  82  83]
  [ 84  85  86  87  88  89  90]
  [ 91  92  93  94  95  96  97]
  [ 98  99 100 101 102 103 104]]]
---
axis=1:
shape: (2, 5, 7)
[[[  0   1   2   3   4   5   6]
  [  7   8   9  10  11  12  13]
  [ 14  15  16  17  18  19  20]
  [ 21  22  23  24  25  26  27]
  [ 28  29  30  31  32  33  34]]

 [[105 106 107 108 109 110 111]
  [112 113 114 115 116 117 118]
  [119 120 121 122 123 124 125]
  [126 127 128 129 130 131 132]
  [133 134 135 136 137 138 139]]]
---
axis=2:
shape: (2, 3, 7)
[[[  0   1   2   3   4   5   6]
  [ 35  36  37  38  39  40  41]
  [ 70  71  72  

In [50]:
test_arr.shape
np.min(test_arr, axis=[0,1])

TypeError: 'list' object cannot be interpreted as an integer

In [53]:
test_arr = np.array([i for i in range(0, 2*3*5*7*11*13*17)]).reshape(2,3,5,7,11,13,17)
print(test_arr.shape)

for axis_v in range(0, len(test_arr.shape)):
    new_arr = np.min(test_arr, axis=axis_v)
    print("axis={}:".format(axis_v))
    print("shape: {}".format(new_arr.shape))
    print("---")

(2, 3, 5, 7, 11, 13, 17)
axis=0:
shape: (3, 5, 7, 11, 13, 17)
---
axis=1:
shape: (2, 5, 7, 11, 13, 17)
---
axis=2:
shape: (2, 3, 7, 11, 13, 17)
---
axis=3:
shape: (2, 3, 5, 11, 13, 17)
---
axis=4:
shape: (2, 3, 5, 7, 13, 17)
---
axis=5:
shape: (2, 3, 5, 7, 11, 17)
---
axis=6:
shape: (2, 3, 5, 7, 11, 13)
---
